# Generated by Django 3.2.7 on 2021-10-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('premise', models.TextField()),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('include_functions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='records_test_exec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.test_cases')),
            ],
        ),
        migrations.CreateModel(
            name='records_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.IntegerField()),
                ('fail_desc', models.TextField()),
                ('test_cases_records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.records_test_exec')),
                ('version_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.version')),
            ],
        ),
    ]
