# Generated by Django 3.2.7 on 2021-10-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
